/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.loccitane.kata

import org.assertj.core.api.Assertions
import org.junit.jupiter.api.Test


class AppTest {

    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        Assertions.assertThat(classUnderTest.greeting).isEqualTo("Hello World!")
    }
}
